version: "3.9"
services:
  database:
    image: mysql:8.3.0
    volumes:
      - "./moovsmart_sprint1.sql:/docker-entrypoint-initdb.d/moovsmart_sprint1.sql"
    container_name: database
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=moovsmart
      - MYSQL_ROOT_PASSWORD=test1234
    ports:
      - "3306:3306"
    healthcheck:
#      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      test: mysqladmin ping -h 127.0.0.1 -u root --password=test1234
      timeout: 30s
      retries: 10

  backend:
    image: csineva/moovsmart-backend:sprint-1
    container_name: backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/moovsmart?serverTimezone=UTC&characterEncoding=utf8
  frontend:
    image: csineva/moovsmart-frontend:sprint-1
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

